#define ES_EQL S(KC_0)
#define ES_MINS KC_SLSH
#define ES_PLUS KC_RBRC
#define ES_NTIL KC_SCLN
#define ES_SCLN S(KC_COMM)
#define ES_SLSH S(KC_7)
#define ES_ACUT KC_QUOT
#define ES_APOS KC_MINS
#define ES_LCBR ALGR(KC_QUOT)
#define ES_RCBR ALGR(KC_NUHS)
#define ES_GRV KC_LBRC
#define ES_DQUO S(KC_2)
#define ES_OVDT S(KC_3)
#define ES_UNDS S(KC_SLSH)
#define ES_AMPR S(KC_6)
#define ES_LPRN S(KC_8)
#define ES_RPRN S(KC_9)
#define ES_ASTR S(KC_RBRC)
#define ES_COLN S(KC_DOT)
#define ES_GRTR S(KC_NUBS)
#define ES_QUES S(KC_MINS)
#define ES_LESS KC_NUBS
#define ES_LBRC ALGR(KC_LBRC)
#define ES_RBRC ALGR(KC_RBRC)
#define ES_IEXL KC_EQL
#define ES_IQUE S(KC_EQL)
#define ES_CIRC S(KC_LBRC)
#define ES_HASH ALGR(KC_3)
#define ES_PIPE ALGR(KC_1)
#define ES_BSLS ALGR(KC_GRV)
